"""empty message

Revision ID: 10df15c840b2
Revises: None
Create Date: 2016-07-06 22:41:28.767875

"""

# revision identifiers, used by Alembic.
revision = '10df15c840b2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cocktails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('recipe', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('alcoholic', sa.Boolean(), nullable=False),
    sa.Column('glass', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cocktail_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cocktail_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id', 'cocktail_id', 'ingredient_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cocktail_ingredients')
    op.drop_table('ingredients')
    op.drop_table('cocktails')
    ### end Alembic commands ###
